---
require:
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - _snippets/*

# ignore class length where unavoidable (e.g., framework requires it)
Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/auth.rb

# ignore block length where unavoidable (e.g., framework requires it)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile
    - app/controllers/**/*

# ignore method length where unavoidable (e.g., framework requires it)
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/controllers/auth.rb
    - app/services/verify_registration.rb
    - app/services/authorize_google_account.rb

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - Rakefile

Style/OpenStructUse:
  Enabled: true
  Exclude:
    - app/models/appointment.rb

Style/Documentation:
  Enabled: true
  Exclude:
    - app/forms/participant_email.rb
    - app/forms/new_event.rb

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - app/models/schedule.rb

Naming/AccessorMethodName:
  Enabled: true
  Exclude:
    - app/services/authorize_google_account.rb

Layout/LineLength:
  Enabled: true
  Exclude:
    - app/services/authorize_google_account.rb

# The single quotes are required to indicate that 'none' is a literal keyword specified by the CSP standard
Lint/PercentStringArray:
  Enabled: true
  Exclude:
    - app/controllers/security.rb