---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://127.0.0.1:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: HQ9VqaywqgAH1QWZEUpMEA6ynvG85uCfYh3FkWpugv4mm8pAb9b0fOPph2VL/dfRVl0hwKwZX0l40KAHQqC1+Q==
  MSG_KEY: CFvkSGnA8dxDz3slwrr3R+MpsX+7aFolJSFvVzfsKYU=
  REDISCLOUD_URL: <provision Redis instance>
  SIGNING_KEY: 7duW3iZtXarA6aNx4Z13xjLY8dQmhg9LDOzh6NUReRw=
  GOOG_CLIENT_ID: 1041602330647-69pv4eprtlo5at4pl9kg2dm8i9oqm2jt.apps.googleusercontent.com
  GOOG_CLIENT_SECRET: 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
  GOOG_OAUTH_URL: https://accounts.google.com/o/oauth2/auth?
  GOOG_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOG_SCOPE: email
  REDIRECT_URI: http://localhost:9292/sso_callback

test:
  API_URL: http://127.0.0.1:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: IzxHaXDlMpOto2k7Wkd2zvCwAJ8mlzPkhKslR7JTp6n0SNuSA2Xixl2Z9r5xskszDPwV0zCGsf5IzHXWWdOKGw==
  MSG_KEY: CFvkSGnA8dxDz3slwrr3R+MpsX+7aFolJSFvVzfsKYU=
  REDISCLOUD_URL: <provision Redis instance>
  SIGNING_KEY: 3aQCCdxhOqXbAOLSBDif/zAjLTLuvobyNJ8ClKu+qno=
  GOOG_CLIENT_ID: 1041602330647-69pv4eprtlo5at4pl9kg2dm8i9oqm2jt.apps.googleusercontent.com
  GOOG_CLIENT_SECRET: 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
  GOOG_OAUTH_URL: https://accounts.google.com/o/oauth2/auth?
  GOOG_TOKEN_URL: https://oauth2.googleapis.com/token
  GOOG_SCOPE: email
  REDIRECT_URI: http://localhost:9292/sso_callback