---
# Rename file to secrets.yml to get started for development or test

development:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secrets
  MSG_KEY: some_key
  REDISCLOUD_URL: <provision Redis instance>

test:
  API_URL: http://localhost:3000/api/v1
  APP_URL: http://localhost:9292
  SESSION_SECRET: some_secret
  MSG_KEY: some_key
  REDISCLOUD_URL: <provision Redis instance>

production:
  API_URL: <provisioned API URL (ending with api/[version])>
  APP_URL: <provisioned app URL (root without ending slash)>
  SESSION_SECRET: <`rake generate:session_secret`>
  MSG_KEY: <`rake generate:msg_key`>
  REDISCLOUD_URL: <provision Redis instance>